---
title: "Using Osprey TLGs with teal"
author: "Adrian Waddell, Nina Qi"
date: "09/20/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Using an osprey outputs with teal

Here is a code to run the `g_spiderplot` in a teal module:


```{r eval=FALSE}
library(teal)
library(osprey)
library(dplyr)

ASL <- rADSL %>% select(STUDYID, USUBJID)
ADTR <- rADTR %>% select(STUDYID, USUBJID, ADY, AVISIT, CHG, PCHG, PARAMCD)

ATR <- ADTR %>% filter(PARAMCD == "SLDINV" & AVISIT != "POST-BASELINE MINIMUM") %>%
      group_by(USUBJID) %>%
      arrange(ADY) %>%
      mutate(PCHG = ifelse(AVISIT == "Screening", 0, PCHG))
ATR <- inner_join(ASL, ATR, by = c("STUDYID", "USUBJID"))

# ANL$USUBJID <- substr(ANL$USUBJID, 14, 18)

x <- teal::init(
  data = list(ASL=ASL, ATR = ATR),
  modules = root_modules(
    tm_data_table(),
    module(
      label = "Spiderplot",
      ui = function(id) {ns <- NS(id); plotOutput(ns("plot"))},
      server = function(input, output, session, datasets) {
        output$plot <- renderPlot({
          
          ATR <- datasets$get_data('ATR',  filtered = TRUE, reactive = TRUE)
          
          osprey::g_spiderplot(marker_x = ATR$ADY, marker_y = ATR$PCHG, marker_id = ATR$USUBJID, line_colby = ATR$STUDYID)
          
        })
      },
      filters = 'ATR'
    )
  )
)




shinyApp(x$ui, x$server)


```
