#' Patient Profile Plot
#'
#' Patient profile plot provides detailed information for a specific subject participated in the study.
#' The plot includes relevant data for one subject that can help correlate adverse events, concomitant medications,
#' exposures, labs, etc. The plotting of patient profile is modularized,
#' each domain plot is one module, generated by function \code{patient_domain_profile},
#' function \code{g_patient_profile} assembles
#' all requested domain plots into one patient profile.
#'
#' @param domain string of domain name to be shown as x-axis label, default is \code{NULL}
#' @param var_names vector to identify each lane
#' @param marker_pos numeric vector for EX, LB and RS domain, numeric data frame with two columns for AE or CM domain
#' @param arrow_end numeric value indicates the end of arrow when arrows are requested
#' @param ytick_at optional break interval of bar length axis
#' @param line_col factor vector to specify color for segments, default is \code{NULL}
#' @param line_col_legend string to be displayed as line color legend title, default is \code{NULL}
#' @param line_col_opt aesthetic values to map color values (named vector to map color values to each name).
#'      If not \code{NULL}, please make sure this contains all posible values for \code{line_col} values,
#'      otherwise color will be assigned by \code{ggplot} default, please note that \code{NULL} needs to be specified
#' @param line_width numeric value for segment width, default is \code{line_width = 1}
#' @param arrow_size numeric value for arrow size, default is \code{arrow_size = 0.1}
#' @param no_enddate_extention numeric value for extending the arrow when end date is missing for AE or CM domain,
#' default is \code{no_enddate_extention = 0}
#' @param marker_color factor vector to specify color for markers, default is \code{NULL}
#' @param marker_color_opt aesthetic values to map color values (named vector to map color values to each name).
#'      If not \code{NULL}, please make sure this contains all posible values for \code{marker_color} values,
#'      otherwise color will be assigned by \code{ggplot} default, please note that \code{NULL} needs to be specified
#' @param marker_color_legend string to be displayed as marker color legend title, default is \code{NULL}
#' @param marker_shape factor vector to specify shape for markers, default is \code{NULL}
#' @param marker_shape_opt aesthetic values to map shape values (named vector to map shape values to each name).
#'      If not \code{NULL}, please make sure this contains all posible values for \code{marker_shape} values,
#'      otherwise shape will be assigned by \code{ggplot} default, please note that \code{NULL} needs to be specified
#' @param marker_shape_legend string to be displayed as marker shape legend title, default is \code{NULL}
#' @param show_days_label boolean value for showing y-axis label, default is \code{TRUE}
#' @param ylim numeric vector for y-axis limit, default is
#'     \code{ylim = c(-28, max(marker_pos) + 5)}
#' @param ylab string to be shown as y-axis label, default is \code{NULL}
#' @param show_title boolean value for showing title of the plot, default is \code{TRUE}
#' @param title string to be shown as title of the plot, default is \code{NULL}
#'
#' @author Xuefeng Hou (houx14) \email{houx14@gene.com} Tina Cho (chot) \email{tina.cho@roche.com}
#' @template author_qit3
#'
#'
#' @return plot object
#' @import dplyr
#' @importFrom rlang .data
#'
#' @export
#'
#' @examples
#'
#' library(random.cdisc.data)
#' library(utils.nest)
#'
#' #Data preparation
#' sl_start_date <- "TRTSDT"
#'
#' ## ADSL
#' rADSL <- radsl(cached = TRUE) # nolint
#' ADSL <-  rADSL %>% # nolint
#'   group_by(.data$USUBJID) %>%
#'   mutate(TRTSDT = as.Date(.data$TRTSDTM, "%d%b%Y"),
#'          max_date = max(as.Date(.data$LSTALVDT, "%d%b%Y"), as.Date(.data$DTHDT, "%d%b%Y"), na.rm=TRUE),
#'   ) %>%
#'   mutate(max_day = as.numeric(as.Date(.data$max_date) -
#'   as.Date(eval(parse(text = sl_start_date)))) + 1) %>%
#'   filter(USUBJID == rADSL$USUBJID[1])
#'
#'
#'
#' ## ADAE
#' rADAE <- radae(cached = TRUE) # nolint
#' ADAE <- left_join(ADSL, rADAE)
#'
#' ADAE <- ADAE %>% # nolint
#'   filter(!is.na(ASTDTM)) %>%
#'   mutate(ASTDY = ceiling(as.numeric(difftime(ASTDTM, as.Date(eval(parse(text = sl_start_date))),
#'                                              units = "days")))) %>%
#'  filter(!is.na(AENDTM)) %>%
#'  mutate(AENDY = ceiling(as.numeric(difftime(AENDTM, as.Date(eval(parse(text = sl_start_date))),
#'                                              units = "days")))) %>%
#'   select(USUBJID, AESOC, AEDECOD, AESER, AETOXGR, AREL, ASTDY, AENDY)
#'
#' ## ADRS
#' rADRS <- radrs(cached = TRUE) #nolint
#' # ADRS
#' ADRS <- left_join(ADSL, rADRS)
#'
#' ADRS <- ADRS %>% # nolint
#'   mutate(ADY = ceiling(as.numeric(difftime(ADTM,
#'   as.Date(eval(parse(text = sl_start_date))), units = "days")))) %>%
#'   select(USUBJID, PARAMCD, PARAM, AVALC, AVAL, ADY, ADTM) %>%
#'   filter(is.na(ADY) == FALSE)
#'
#' #ADRS_var <- c("OVR", "BOR", "CBOR")
#' #ADRS <- ADRS %>%
#' #filter(PARAMCD %in% ADRS_var)
#'
#' ## ADCM
#' rADCM <- radcm(cached = TRUE) # nolint
#' # ADCM
#' ADCM <- left_join(ADSL, rADCM)
#' ADCM <- ADCM %>% # nolint
#'   filter(!is.na(ASTDTM)) %>%
#'   mutate(ASTDY = ceiling(as.numeric(difftime(ASTDTM, as.Date(eval(parse(text = sl_start_date))),
#'                                              units = "days")))) %>%
#'  filter(!is.na(AENDTM)) %>%
#'   mutate(AENDY = ceiling(as.numeric(difftime(AENDTM, as.Date(eval(parse(text = sl_start_date))),
#'                                              units = "days")))) %>%
#'   select(USUBJID, CMDECOD, ASTDTM, AENDTM, ASTDY, AENDY)
#'
#' if (length(unique(ADCM$USUBJID)) > 0) {
#'   ADCM <- ADCM[which(ADCM$AENDY >= -28 | is.na(ADCM$AENDY) == TRUE
#'   & is.na(ADCM$ASTDY) == FALSE), ]
#' }
#'
#' ## ADEX
#' rADEX <- radex(cached = TRUE) # nolint
#' ADEX <- left_join(ADSL, rADEX)
#'
#' ADEX <- ADEX %>% # nolint
#'   filter(PARCAT1 == "INDIVIDUAL" & PARAMCD == "DOSE" & !is.na(AVAL)) %>%
#'  filter(!is.na(ASTDTM)) %>%
#'   mutate(ASTDT_dur = as.numeric(as.Date(ASTDTM, "%d-%b-%y") -
#'   as.Date(eval(parse(text = sl_start_date)), "%d%b%Y")) + 1) %>%
#'   select(USUBJID, ASTDTM, PARCAT2, AVAL, AVALU, PARAMCD, TRTSDT, ASTDT_dur)
#'
#' ADEX <- split(ADEX, ADEX$USUBJID) %>% # nolint
#'   lapply(function(pinfo) {
#'     pinfo %>%
#'       arrange(PARCAT2, PARAMCD) %>%
#'       ungroup %>%
#'       mutate(diff = c(0, diff(AVAL, lag = 1))) %>%
#'       mutate(Modification = case_when(diff < 0 ~ "Decrease",
#'                                       diff > 0 ~ "Increase",
#'                                       diff == 0 ~ "None")) %>%
#'       mutate(ASTDT_dur = as.numeric(as.Date(ASTDTM, "%d-%b-%y") -
#'                                       as.Date(eval(parse(text = sl_start_date)), "%d%b%Y")) + 1)
#'   })  %>%
#'   Reduce(rbind, .) %>%
#'   as.data.frame
#'
#'
#' ## ADLB
#' rADLB <- radlb(cached = TRUE) # nolint
#' ADLB <- left_join(ADSL, rADLB)
#'
#' ADLB <- ADLB %>% # nolint
#'   group_by(USUBJID) %>%
#'   mutate(LBSTRESC = as.numeric(.data$LBSTRESC),
#'          ANRIND = factor(.data$ANRIND, levels = c("HIGH", "LOW", "NORMAL"))) %>%
#'   filter(is.na(.data$LBSTRESC) == FALSE & is.na(.data$ANRIND) == FALSE) %>%
#'   as.data.frame
#' ADLB <- ADLB %>%  # nolint
#'   mutate(ADY = ceiling(as.numeric(difftime(.data$ADTM,
#'                                            as.Date(eval(parse(text = sl_start_date))),
#'                                            units = "days"))))
#'
#'
#'
#'
#' # Example 1 "ADEX"
#' p1 <- patient_domain_profile(domain = "ADEX",
#'                              var_names = ADEX$PARCAT2,
#'                              marker_pos = ADEX$ASTDT_dur,
#'                              arrow_end = ADSL$max_day,
#'                              ytick_at = waiver(),
#'                              line_col = NULL,
#'                              line_col_legend = NULL,
#'                              line_col_opt = NULL,
#'                              line_width = 1,
#'                              arrow_size = 0.1,
#'                              no_enddate_extention = 0,
#'                              marker_color = factor(ADEX$Modification),
#'                              marker_color_opt =  c("Increase" = "red",
#'                              "Decrease" = "green", "None" = "blue"),
#'                              marker_color_legend = NULL,
#'                              marker_shape = factor(ADEX$Modification),
#'                              marker_shape_opt = c("Increase" = 24, "Decrease" = 25, "None" = 23),
#'                              marker_shape_legend = "Dose Modification",
#'                              show_days_label = TRUE,
#'                              ylim = c(-28, 250),
#'                              ylab = "Study Days",
#'                              title = paste("Patient Profile: ", ADSL$USUBJID))
#'p1
#'
#' # Example 2 "ADAE"
#' # Note that ASTDY is represented by a circle and AENDY is represented by a square.
#' # If AENDY and ASTDY occur on the same day only AENDY will be shown.
#'
#' p2 <- patient_domain_profile(domain = "ADAE",
#'                              var_names = ADAE$AEDECOD,
#'                              marker_pos = ADAE[, c("ASTDY", "AENDY")],
#'                              arrow_end = ADSL$max_day,
#'                              ytick_at = waiver(),
#'                              line_col = factor(ADAE$AESER),
#'                              line_col_legend = "Serious",
#'                              line_col_opt = c("Y" = "red", "N" = "blue"),
#'                              line_width = 1,
#'                              arrow_size = 0.1,
#'                              no_enddate_extention = 50,
#'                              marker_color = factor(ADAE$AETOXGR),
#'                              marker_color_opt = c("1" = "green", "2" = "blue",
#'                                                   "3" = "yellow", "4" = "orange", "5" = "red"),
#'                              marker_color_legend = "Grade",
#'                              marker_shape = NULL,
#'                              marker_shape_opt = NULL,
#'                              marker_shape_legend = NULL,
#'                              show_days_label = TRUE,
#'                              ylim = c(-28, 250),
#'                              ylab = "Study Days",
#'                              title = paste("Patient Profile: ", ADSL$USUBJID))
#'p2
#'
#' # Example 3 "ADRS"
#' p3 <- patient_domain_profile(domain = "ADRS",
#'                              var_names = ADRS$PARAMCD,
#'                              marker_pos = ADRS$ADY,
#'                              arrow_end = ADSL$max_day,
#'                              ytick_at = waiver(),
#'                              line_col = NULL,
#'                              line_col_legend = NULL,
#'                              line_col_opt = NULL,
#'                              line_width = 1,
#'                              arrow_size = 0.1,
#'                              no_enddate_extention = 0,
#'                              marker_color = factor(ADRS$AVALC),
#'                              marker_color_opt =  c("CR" = "green", "PR" = "blue",
#'                              "SD" = "yellow", "PD" = "red", "NE" = "pink",
#'                              "Y" = "lightblue", "N" = "darkred"),
#'                              marker_color_legend = NULL,
#'                              marker_shape = factor(ADRS$AVALC),
#'                              marker_shape_opt = c("CR" = 21, "PR" = 24,
#'                              "SD" = 23, "PD" = 22, "NE" = 14,
#'                              "Y" = 11, "N" = 8),
#'                             marker_shape_legend = "Response",
#'                              show_days_label = TRUE,
#'                              ylim = c(-28, 250),
#'                              ylab = "Study Days",
#'                              title = paste("Patient Profile: ", ADSL$USUBJID))
#'p3
#'
#' # Example 4 "ADCM"
#' p4 <- patient_domain_profile(domain = "ADCM",
#'                              var_names = ADCM$CMDECOD,
#'                              marker_pos = ADCM[, c("ASTDY", "AENDY")],
#'                              arrow_end = ADSL$max_day,
#'                              ytick_at = waiver(),
#'                              line_col = NULL,
#'                              line_col_legend = NULL,
#'                              line_col_opt = "orange",
#'                              line_width = 1,
#'                              arrow_size = 0.1,
#'                              no_enddate_extention = 50,
#'                              marker_color = NULL,
#'                              marker_color_opt = "orange",
#'                              marker_color_legend = NULL,
#'                              marker_shape = NULL,
#'                              marker_shape_opt = NULL,
#'                              marker_shape_legend = NULL,
#'                              show_days_label = TRUE,
#'                              ylim = c(-28, 250),
#'                              ylab = "Study Days",
#'                              title = paste("Patient Profile: ", ADSL$USUBJID))
#'p4
#'
#' # Example 5 "ADLB"
#' p5 <- patient_domain_profile(domain = "ADLB",
#'                              var_names = ADLB$LBTESTCD,
#'                              marker_pos = ADLB$ADY,
#'                              arrow_end = ADSL$max_day,
#'                              ytick_at = waiver(),
#'                              line_col = NULL,
#'                              line_col_legend = NULL,
#'                              line_col_opt = NULL,
#'                              line_width = 1,
#'                              arrow_size = 0.1,
#'                              no_enddate_extention = 0,
#'                              marker_color = factor(ADLB$ANRIND),
#'                              marker_color_opt =  c("HIGH" = "red", "LOW" = "blue",
#'                                                    "NORMAL" = "green", "NA" = "green"),
#'                              marker_color_legend = NULL,
#'                              marker_shape = factor(ADLB$ANRIND),
#'                              marker_shape_opt = c("HIGH" = 24, "LOW" = 25,
#'                                                   "NORMAL" = 23, "NA" = 23),
#'                              marker_shape_legend = "Labs Abnormality",
#'                              show_days_label = TRUE,
#'                              ylim = c(-30, 250),
#'                              ylab = "Study Days",
#'                              title = paste("Patient Profile: ", ADSL$USUBJID))
#'p5

patient_domain_profile <- function(domain = NULL,
                                   var_names,
                                   marker_pos,
                                   arrow_end,
                                   ytick_at = 40,
                                   line_col = NULL,
                                   line_col_legend = NULL,
                                   line_col_opt = NULL,
                                   line_width = 1,
                                   arrow_size = 0.1,
                                   no_enddate_extention = 0,
                                   marker_color = NULL,
                                   marker_color_opt = NULL,
                                   marker_color_legend = NULL,
                                   marker_shape = NULL,
                                   marker_shape_opt = NULL,
                                   marker_shape_legend = NULL,
                                   show_days_label = TRUE,
                                   ylim = c(-28, max(marker_pos) + 5),
                                   ylab = NULL,
                                   show_title = TRUE,
                                   title = NULL) {

  marker_data <- data.frame(var_names,
                            marker_pos = if (is.null(marker_pos))
                              tern:::to_n("x", length(var_names)) else marker_pos,
                            marker_shape = if (is.null(marker_shape))
                              tern:::to_n("x", length(var_names)) else marker_shape,
                            marker_color = if (is.null(marker_color))
                              tern:::to_n("x", length(var_names)) else marker_color)

  # plot lines
  if (length(dim(marker_pos)) == 2) {
    line_data <- data.frame(var_names,
                            line_col = if (is.null(line_col)) tern:::to_n("x", length(var_names)) else line_col,
                            line_start = marker_pos[, 1],
                            line_end = marker_pos[, 2],
                            line_min = rep(ylim[1], length(var_names)),
                            line_max = rep(arrow_end + no_enddate_extention, length(var_names)))
    names(line_data) <- c("var_names", "line_col", "line_start", "line_end", "line_min", "line_max")


    p <- ggplot() +
      geom_segment(data = line_data[is.na(line_data$line_end) == FALSE, ],
                   aes(x = var_names, y = line_start, xend = var_names, yend = line_end, color = line_col),
                   lineend = "round", linejoin = "round",
                   size = line_width, arrow = NULL, show.legend = NA) +
      scale_y_continuous(limits = ylim, breaks = ytick_at, expand = c(0, 0)) +
      coord_flip(xlim = c(1, length(unique(var_names)))) +
      geom_segment(data = line_data[is.na(line_data$line_end) == TRUE, ],
                   aes(x = var_names, y = pmax(line_start, line_min, na.rm = TRUE),
                       xend = var_names, yend = line_max, color = line_col),
                   lineend = "round", linejoin = "round",
                   size = line_width, show.legend = FALSE,
                   arrow = arrow(length = unit(arrow_size, "inches")))

    if (!is.null(line_col_opt)) {
      p <- p + scale_color_manual(breaks = line_data$line_col,
                                  values = line_col_opt)
    } else{
      p <- p + scale_color_manual(breaks = line_data$line_col,
                                  values = c(1:25))
    }

    if (!is.null(line_col)) {
      p <- p + guides(color = guide_legend(line_col_legend, order = 1))
    } else {
      p <- p + guides(color = FALSE)
    }

    # plot markers
    p <- p + geom_point(data = marker_data, aes(x = var_names,
                                                y = marker_data[, 2],
                                                fill = factor(marker_color)),
                        shape = 21, #-as.hexmode("25BA"),
                        size = 5,
                        na.rm = TRUE) +
      geom_point(data = marker_data, aes(x = var_names,
                                         y = marker_data[, 3],
                                         fill = factor(marker_color)),
                 shape = 22, #-as.hexmode("25C4"),
                 size = 3, na.rm = TRUE)

    if (!is.null(marker_color_opt)) {
      p <- p + scale_fill_manual(breaks = marker_data$marker_color,
                                 values = marker_color_opt)
    } else{
      p <- p + scale_fill_manual(breaks = marker_data$marker_color,
                                 values = c(1:25))
    }


    p <- p + theme_bw() +
      theme(
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black")
      ) +
      ylab(ylab) + xlab(domain)

    if (!is.null(marker_color)) {
      p <- p + guides(fill = guide_legend(marker_color_legend, order = 2))
    } else {
      p <- p + guides(fill = FALSE)
    }

    p <- p + guides(shape = guide_legend("Shape", order = 3))

    p <- p + scale_shape_manual(values = c(21, 22)) +
      guides(shape = guide_legend(title = "Shape", override.aes = list(label = c("Start", "End")), order = 3))

    if (!is.null(marker_shape)) {
      p <- p + guides(shape = guide_legend(marker_shape_legend, order = 3))
    } else {
      p <- p + guides(shape = FALSE)
    }

  } else{
    p <- ggplot() +
      geom_point(data = marker_data, aes(x = var_names,
                                         y = marker_pos,
                                         shape = marker_shape,
                                         fill = marker_color),
                 size = 3, na.rm = TRUE) +
      scale_y_continuous(limits = ylim, breaks = ytick_at, expand = c(0, 0)) +
      coord_flip(xlim = c(1, length(unique(var_names)))) +
      theme_bw() +
      theme(
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black")
      ) +
      ylab(ylab) + xlab(domain)

    if (is.null(marker_color_legend)) {
      if (length(setdiff(marker_color, marker_shape)) == 0) {
        marker_color_legend <- marker_shape_legend
      }
    }

    if (is.null(marker_shape_legend)) {
      if (length(setdiff(marker_color, marker_shape)) == 0) {
        marker_shape_legend <- marker_color_legend
      }
    }

    if (!is.null(marker_color_opt)) {
      p <- p + scale_fill_manual(name = marker_color_legend,
                                 breaks = marker_data$marker_color,
                                 values = marker_color_opt)
    } else{
      p <- p + scale_fill_manual(name = marker_color_legend,
                                 breaks = marker_data$marker_color,
                                 values = c(1:25))
    }

    if (!is.null(marker_shape_opt)) {
      p <- p + scale_shape_manual(name = marker_shape_legend,
                                  breaks = marker_data$marker_shape,
                                  values = marker_shape_opt)
    } else{
      p <- p + scale_shape_manual(name = marker_shape_legend,
                                  breaks = marker_data$marker_shape,
                                  values = c(1:25))
    }

  }

  # plot title and labels
  if (show_title == TRUE) {
    p <- p +
      labs(title = title) +
      theme(plot.title = element_text(face = "bold"))
  }

  # Plot y axis label
  if (show_days_label == FALSE) {
    p <- p + theme_bw() +
      theme(
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = rel(0.8)),
        legend.title = element_text(size = 10),
        legend.spacing.y = unit(0, "cm"),
        legend.key.height = unit(1, "line"),
        legend.margin = margin(t = 0, b = 0, r = 0.5, l = 0, unit = "cm"),
        plot.margin = margin(t = 0, b = 0, r = 0.5, l = 0.5, unit = "cm")
      )
  } else{
    p <- p + theme_bw() +
      theme(
        panel.background = element_blank(),
        panel.grid = element_blank(),
        axis.line = element_line(colour = "black"),
        legend.title = element_text(size = 10),
        legend.spacing.y = unit(0, "cm"),
        legend.key.height = unit(1, "line"),
        legend.margin = margin(t = 0, b = 0, r = 0.5, l = 0, unit = "cm"),
        plot.margin = margin(t = 0, b = 0, l = 0.5, r = 0.5, unit = "cm")
      )
  }

  p
}

#' Patient Profile Plot
#'
#' Patient profile plot provides detailed information for a specific subject participating in the study.
#' The plot includes relevant data for one subject that can help correlate adverse events, concomitant medications,
#' exposures, labs, etc. The plotting of patient profile is modularized,
#' each domain plot is one module, generated by function \code{patient_domain_profile},
#' function \code{g_patient_profile} assembles
#' all requested domain plots into one patient profile.
#'
#' ADSL, ADEX, ADAE, ADRS, ADCM and ADLB data must be provided.
#' If there is a missing dataset, assign a NULL value to it. ie) ADRS <- NULL
#' prior to running the patient profile plot.
#'
#' @param select_ex boolean value for showing EX domain plot, default is \code{TRUE}
#' @param select_ae boolean value for showing AE domain plot, default is \code{TRUE}
#' @param select_rs boolean value for showing RS domain plot, default is \code{TRUE}
#' @param select_cm boolean value for showing CM domain plot, default is \code{TRUE}
#' @param select_lb boolean value for showing LB domain plot, default is \code{TRUE}
#' @param ex_data dataframe for EX domain dataset
#' @param ex_var_names vector to identify each lane of EX domain plot
#' @param ae_data dataframe for AE domain dataset
#' @param ae_var_names vector to identify each lane of AE domain plot
#' @param ae_line_col factor vector to specify color for segments of AE domain plot
#' @param ae_line_col_legend string to be displayed as line color legend title of AE domain plot, default is \code{NULL}
#' @param ae_line_col_opt aesthetic values to map line color values of AE domain plot
#'      (named vector to map color values to each name).
#'      If not \code{NULL}, please make sure this contains all posible values for \code{ae_line_col} values,
#'      otherwise color will be assigned by \code{ggplot} default, please note that \code{NULL} needs to be specified
#' @param rs_data dataframe for RS domain dataset
#' @param rs_var_names vector to identify each lane of RS domain plot
#' @param cm_data dataframe for CM domain dataset
#' @param cm_var_names vector to identify each lane of CM domain plot
#' @param lb_data dataframe for LB domain dataset
#' @param lb_var_names vector to identify each lane of LB domain plot
#' @param arrow_end_day numeric value indicates the end of arrow when arrows are requested
#' @param ylim numeric vector for y-axis limit that will be shared by all domain plots, default is
#'      \code{ylim = c(-28, 250)}
#' @param ylab string to be shown as y-axis label, default is \code{"Study Days"}
#' @param title string to be shown as title of the plot, default is \code{"Patient Profile"}
#'
#' @author Xuefeng Hou (houx14) \email{houx14@gene.com}
#' @template author_qit3
#'
#' @importFrom cowplot plot_grid
#'
#' @return plot object
#'
#' @export
#'
#' @examples
#' library(osprey)
#'
#' # Example Patient Profile plot 5 domains
#' g_patient_profile(select_ex = TRUE,
#'                   select_ae = TRUE,
#'                   select_rs = TRUE,
#'                   select_cm = TRUE,
#'                   select_lb = TRUE,
#'                   ex_data = ADEX,
#'                   ex_var_names = ADEX$PARCAT2,
#'                   ae_data = ADAE,
#'                   ae_var_names = ADAE$AEDECOD,
#'                   ae_line_col = factor(ADAE$AESER),
#'                   ae_line_col_legend = "Serious",
#'                   ae_line_col_opt = c("Y" = "red", "N" = "blue"),
#'                   rs_data = ADRS,
#'                   rs_var_names = ADRS$PARAMCD,
#'                   cm_data = ADCM,
#'                   cm_var_names = ADCM$CMDECOD,
#'                   lb_data = ADLB,
#'                   lb_var_names = ADLB$LBTESTCD,
#'                   arrow_end_day = ADSL$max_day,
#'                   ylim = c(-28, 250),
#'                   ylab = "Study Days",
#'                   title = paste("Patient Profile: ", ADSL$USUBJID))

g_patient_profile <- function(select_ex = TRUE,
                              select_ae = TRUE,
                              select_rs = TRUE,
                              select_cm = TRUE,
                              select_lb = TRUE,
                              ex_data,
                              ex_var_names,
                              ae_data,
                              ae_var_names,
                              ae_line_col,
                              ae_line_col_legend = NULL,
                              ae_line_col_opt = NULL,
                              rs_data,
                              rs_var_names,
                              cm_data,
                              cm_var_names,
                              lb_data,
                              lb_var_names,
                              arrow_end_day,
                              ylim = c(-28, 250),
                              ylab = "Study Days",
                              title = "Patient Profile") {

  #Check if we have data for each of these plots
  if (dim(ADEX)[1] == 0 || is.null(ADEX)) {
    select_ex <- FALSE
    warning("No AEX data for this subject")

  }

  if (dim(ADAE)[1] == 0 || is.null(ADAE)) {
    select_ae <- FALSE
    warning("No AAE data for this subject")

  }

  if (dim(ADRS)[1] == 0 || is.null(ADRS)) {
    select_rs <- FALSE
    warning("No ARS data for this subject")

  }

  if (dim(ADCM)[1] == 0 || is.null(ADCM)) {
    select_cm <- FALSE
    warning("No ACM data for this subject")
  }
  if (dim(ADLB)[1] == 0 || is.null(ADLB)) {
    select_lb <- FALSE
    warning("No ALB data for this subject")
  }

  select_list <- c(select_ex, select_ae, select_rs, select_cm, select_lb)


  show_days_label <- c(FALSE, FALSE, FALSE, FALSE, FALSE)
  show_days_label[max(which(select_list == TRUE))] <- TRUE

  show_title <- c(FALSE, FALSE, FALSE, FALSE, FALSE)
  show_title[min(which(select_list == TRUE))] <- TRUE

  # Domain "ADEX"
  if (select_ex == TRUE) {
    p1 <- patient_domain_profile(domain = "Exposure (ADEX)",
                                 var_names = ex_var_names,
                                 marker_pos = ex_data$ASTDT_dur,
                                 arrow_end = arrow_end_day,
                                 ytick_at = waiver(),
                                 line_col = NULL,
                                 line_col_legend = NULL,
                                 line_col_opt = NULL,
                                 line_width = 1,
                                 arrow_size = 0.1,
                                 no_enddate_extention = 0,
                                 marker_color = factor(ex_data$Modification),
                                 marker_color_opt =  c("Increase" = "red", "Decrease" = "green", "None" = "blue"),
                                 marker_color_legend = NULL,
                                 marker_shape = factor(ex_data$Modification),
                                 marker_shape_opt = c("Increase" = 24, "Decrease" = 25, "None" = 23),
                                 marker_shape_legend = "Dose Modification",
                                 show_days_label = show_days_label[1],
                                 ylim = ylim,
                                 ylab = ylab,
                                 show_title = show_title[1],
                                 title = title)

  } else {
    p1 <- NULL
  }

  # Domain "ADAE"
  if (select_ae == TRUE) {
    p2 <- patient_domain_profile(domain = "Adverse Event (ADAE)",
                                 var_names = ae_var_names,
                                 marker_pos = ae_data[, c("ASTDY", "AENDY")],
                                 arrow_end = arrow_end_day,
                                 ytick_at = waiver(),
                                 line_col = ae_line_col,
                                 line_col_legend = ae_line_col_legend,
                                 line_col_opt = ae_line_col_opt,
                                 line_width = 1,
                                 arrow_size = 0.1,
                                 no_enddate_extention = 0.1,
                                 marker_color = factor(ae_data$AETOXGR),
                                 marker_color_opt = c("1" = "green", "2" = "blue",
                                                      "3" = "yellow", "4" = "orange", "5" = "red"),
                                 marker_color_legend = "Grade",
                                 marker_shape = NULL,
                                 marker_shape_opt = NULL,
                                 marker_shape_legend = NULL,
                                 show_days_label = show_days_label[2],
                                 ylim = ylim,
                                 ylab = ylab,
                                 show_title = show_title[2],
                                 title = title)
  } else{
    p2 <- NULL
  }


  # Domain "ADRS"
  if (select_rs == TRUE) {
    p3 <- patient_domain_profile(domain = "Tumor Response (ADRS)",
                                 var_names = rs_var_names,
                                 marker_pos = rs_data$ADY,
                                 arrow_end = arrow_end_day,
                                 ytick_at = waiver(),
                                 line_col = NULL,
                                 line_col_legend = NULL,
                                 line_col_opt = NULL,
                                 line_width = 1,
                                 arrow_size = 0.1,
                                 no_enddate_extention = 0,
                                 marker_color = factor(rs_data$AVALC),
                                 marker_color_opt =  c("CR" = "green", "PR" = "blue", "SD" = "yellow",
                                                       "PD" = "red", "NE" = "pink", "Y" = "lightblue", "N" = "darkred"),
                                 marker_color_legend = NULL,
                                 marker_shape = factor(rs_data$AVALC),
                                 marker_shape_opt = c("CR" = 21, "PR" = 24, "SD" = 23, "PD" = 22, "NE" = 14,
                                                      "Y" = 11, "N" = 8),
                                 marker_shape_legend = "Response",
                                 show_days_label = show_days_label[3],
                                 ylim = ylim,
                                 ylab = ylab,
                                 show_title = show_title[3],
                                 title = title)
  } else {
    p3 <- NULL
  }


  # Domain "ADCM"
  if (select_cm == TRUE) {
    p4 <- patient_domain_profile(domain = "Concomitant Med (ADCM)",
                                 var_names = cm_var_names,
                                 marker_pos = cm_data[, c("ASTDY", "AENDY")],
                                 arrow_end = arrow_end_day,
                                 ytick_at = waiver(),
                                 line_col = NULL,
                                 line_col_legend = NULL,
                                 line_col_opt = "orange",
                                 line_width = 1,
                                 arrow_size = 0.1,
                                 no_enddate_extention = 0.1,
                                 marker_color = NULL,
                                 marker_color_opt = "orange",
                                 marker_color_legend = NULL,
                                 marker_shape = NULL,
                                 marker_shape_opt = NULL,
                                 marker_shape_legend = NULL,
                                 show_days_label = show_days_label[4],
                                 ylim = ylim,
                                 ylab = ylab,
                                 show_title = show_title[4],
                                 title = title)
  } else {
    p4 <- NULL
  }

  # Domain "ADLB"
  if (select_lb == TRUE) {
    p5 <- patient_domain_profile(domain = "Laboratory (ADLB)",
                                 var_names = lb_var_names,
                                 marker_pos = lb_data$ADY,
                                 arrow_end = arrow_end_day,
                                 ytick_at = waiver(),
                                 line_col = NULL,
                                 line_col_legend = NULL,
                                 line_col_opt = NULL,
                                 line_width = 1,
                                 arrow_size = 0.1,
                                 no_enddate_extention = 0,
                                 marker_color = factor(lb_data$ANRIND),
                                 marker_color_opt =  c("HIGH" = "red", "LOW" = "blue",
                                                       "NORMAL" = "green"),
                                 marker_color_legend = NULL,
                                 marker_shape = factor(lb_data$ANRIND),
                                 marker_shape_opt = c("HIGH" = 24, "LOW" = 25, "NORMAL" = 23),
                                 marker_shape_legend = "Labs Abnormality",
                                 show_days_label = show_days_label[5],
                                 ylim = ylim,
                                 ylab = ylab,
                                 show_title = show_title[5],
                                 title = title)
  } else {
    p5 <- NULL
  }

  # Assemble domain plots into patient profile plot
  n_domain <- sum(select_ex, select_ae, select_rs, select_cm, select_lb)

  plot_list <- list(p1, p2, p3, p4, p5)

  nline_ex <- length(unique(ex_var_names))
  if (nline_ex <= 10 & nline_ex > 0) {
    nline_ex <- 10
  }

  nline_ae <- length(unique(ae_var_names))
  if (nline_ae <= 10 & nline_ae > 0) {
    nline_ae <- 10
  }

  nline_rs <- length(unique(rs_var_names))
  if (nline_rs <= 10 & nline_rs > 0) {
    nline_rs <- 10
  }

  nline_cm <- length(unique(cm_var_names))
  if (nline_cm <= 10 & nline_cm > 0) {
    nline_cm <- 10
  }

  nline_lb <- length(unique(lb_var_names))
  if (nline_lb <= 10 & nline_lb > 0) {
    nline_lb <- 10
  }

  nline_total <- sum(nline_ex, nline_ae, nline_rs, nline_cm, nline_lb, na.rm = TRUE)

  sbplt_ht <- c(nline_ex / nline_total,
                nline_ae / nline_total,
                nline_rs / nline_total,
                nline_cm / nline_total,
                nline_lb / nline_total)

  p_list <- rep(list(NA), n_domain)
  subplot_height <- rep(NA, n_domain)

  j <- 1
  for (i in seq_len(length(select_list))) {
    if (select_list[i] == TRUE) {
      p_list[[j]] <- plot_list[[i]]
      subplot_height[j] <- sbplt_ht[i]
      j <- j + 1
    }
  }

  plot_grid(plotlist = p_list, nrow = j - 1, align = "v", axis = "lr", rel_heights = subplot_height)
}
