#import tern functions
duplicate_with_var <- tern:::duplicate_with_var
check_col_by <- tern:::check_col_by
stack_rtables <- tern:::stack_rtables
count_perc_col_N <- tern:::count_perc_col_N
indent_table <- tern:::indent_table
add_ae_class <- tern:::add_ae_class
check_same_N <- tern:::check_same_N
to_n <- tern:::to_n
var_relabel <- tern:::var_relabel
t_max_grade_per_id <- tern:::t_max_grade_per_id
shift_label_table <- tern:::shift_label_table
